# <center> PART A <center>

In [5]:
import numpy as np

poisson_ratio = 0.1
yield_strenght = [220, -320]
ultimate_strenght = [305, -410]

#Set everyhting in MPa
E = 200 *10e3

sigma_x, sigma_y = 50, 150
tau_xy = 150

compliance_matrix = np.array([[1/E, -poisson_ratio/E, 0],
                     [-poisson_ratio/E, 1/E, 0],
                     [0, 0, 1/(E/(2*(1+poisson_ratio)))]])



strain_set = np.array([sigma_x, sigma_y, tau_xy]) @ compliance_matrix
strain_set

array([1.75e-05, 7.25e-05, 1.65e-04])

In [6]:
stress_matrix = [[sigma_x, tau_xy],[tau_xy, sigma_y]]
eigenvalues = np.linalg.eigvals(stress_matrix)
eigenvalues

array([-58.11388301, 258.11388301])

#### <center> The material will have permanent deformation, but it will not break <center>

# <center> PART B <center>

In [7]:
sigma_x, sigma_y = 150, 150
tau_xy = 50

stress_array = np.array([sigma_x, sigma_y, tau_xy])

strain_set = stress_array @ compliance_matrix
strain_set

array([6.75e-05, 6.75e-05, 5.50e-05])

In [8]:
# Calculate eigenvalues of stress_array
stress_matrix = np.array([[sigma_x, tau_xy],
                          [tau_xy, sigma_y]])
eigenvalues = np.linalg.eigvals(stress_matrix)
eigenvalues

array([200., 100.])

### <center> The material will not have permanent deformation <center>